version: '3'
services:
  nginx:
    image: nginx:1.15.6
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/src

