version: '3'
services:
  nginx:
    container_name: nginx_02
    # image: nginx:1.15.6    # OSのバージョンのせいか、aptが上手く動かない（パッケージのいくつかが Not Found）
    image: nginx:1.25.0
    ports:
      - "8000:80"
    depends_on:
      - php
    volumes:
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/src

  php:
    container_name: php_nginx_02
    build: ./containers/php
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    user: www-data
    environment:
      - APP_ENV=local

